version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    # Use standard Postgres port
    command: -p 5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
  fastapi:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    # Separate script for Gunicorn
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis
